# demo_setup.yml
---
- name: Launch EC2
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
         key_name: my_key
         group: Basic Access
         instance_type: t2.micro
         image: "{{ ami_id }}"
         wait: true
         exact_count: 1
         instance_tags:
            Name: Demo
      register: ec2
